// <auto-generated />
namespace Book_Reading_Event_DAO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class aakash : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aakash));
        
        string IMigrationMetadata.Id
        {
            get { return "202002061042257_aakash"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
